name: ADMT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Set the Python version you need
  copy_to_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Change directory to Demo_project
        run:  cd Demo_project
      - name: Create prod directory
        run: mkdir -p prod
      - name: Copy file to prod
        run: cp Demo_project/dev/dev.py Demo_project/prod/prod.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Copy dev.py to prod"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
  test:
      - name: Install dependencies
        run: pip install -r requirements.txt
      
        - name: Run tests
         run: pytest

  copy_confirmation:
    runs-on: ubuntu-latest
    needs: copy_to_prod
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line confirmation
        run: echo "File Copied!"