name: ADMT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 

  copy_to_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Change directory to demoproject
        # run: cd Demo_project
      # - name: Create prod directory
        # run: mkdir -p prod
      # - name: Copy file to prod
        run: cp demoproject/dev/dev.py demoproject/prod/prod.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Copy dev.py to prod"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"

  

  copy_confirmation:
    runs-on: ubuntu-latest
    needs: copy_to_prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a one-line confirmation
        run: echo "File Copied!"